version: '3.4'

services:
  dwbot:
    image: ${DOCKER_REGISTRY-}dwbot
    build:
      context: .
      dockerfile: DWBot/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BotConfiguration__BotToken=$BOTTOKEN
    restart: always
    volumes:
      - ./database:/app/database:rw
      - ./logs:/app/logs:rw